#!/usr/bin/env bash

sudo pacman -Sy
# Set up YAY (AUR Helper)
cd ~
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
cd ~
rm -rf ~/yay

# Install applications
pacman=(
xorg
xorg-xinit
chromium
awesome
alacritty
zsh
dmenu
ffmpeg
sxiv
maim
xclip
ttf-hack
ttf-joypixels 
noto-fonts 
noto-fonts-cjk 
noto-fonts-emoji
dunst
libnotify
pulseaudio-alsa
pulsemixer
pamixer
youtube-dl
fzf
unclutter
xdotool
zip
unzip
zathura
zathura-pdf-mupdf
ttf-jetbrains-mono
fortune-mod
aria2
mpv
tmate
ranger
feh
    )

yay=(
lain-git
awesome-freedesktop-git
picom-jonaburg-git
nerd-fonts-hack
otf-font-awesome-5-free
otf-font-awesome-4
    )

sudo pacman -S --noconfirm ${pacman[@]}
yay -S --noconfirm ${yay[@]}

#Pull down dotfiles from Github
cd ~
cp -a ~/dots/. ~/
rm -rf ~/dots

#change default shell
chsh -s /usr/bin/zsh
echo "Installation complete"

sleep 2

exit