#!/usr/bin/env bash

# Set up YAY (AUR Helper)
cd ~
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
cd ~
rm -rf ~/yay

# Install applications
pacman=(
xorg
xorg-xinit
chromium
awesome
alacritty
zsh
dmenu
ffmpeg
sxiv
maim
xclip
picom
ttf-hack
ttf-joypixels 
noto-fonts 
noto-fonts-cjk 
noto-fonts-emoji
dunst
libnotify
pulseaudio-alsa
pulsemixer
pamixer
youtube-dl
fzf
unclutter
xdotool
zip
unzip
zathura
zathura-pdf-mupdf
ttf-jetbrains-mono
fortune-mod
aria2
mpv
tmate
ranger
python-pip
feh
    )

yay=(
spotify
lain-git
awesome-freedesktop-git
picom-jonaburg-git
nerd-fonts-hack
otf-font-awesome-5-free
otf-font-awesome-4
    )

pacman -S --noconfirm ${pacman[@]}
yay -S --noconfirm ${yay[@]}

# xinitrc stuff
cp /etc/X11/xinit/xinitrc ~/.xinitrc
sed -i '51,55d' ~/.xinitrc
sed -i -r '/^\s*$/d' ~/.xinitrc
echo "exec awesome" >> ~/.xinitrc

#Pull down dotfiles from Github
cd ~
git clone https://github.com/ghostr72/dots.git

#Linking up dotfiles & stuff
mv -v dots/.* ~/ && rm -rf dots

echo "Installation complete, restart, or run 'startx' to get started"
